# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports: 
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: example
  # pg_proxy:
  #   image: ghcr.io/neondatabase/wsproxy:latest
  #   environment:
  #     APPEND_PORT: 'postgres:5432'
  #     ALLOW_ADDR_REGEX: '.*'
  #     LOG_TRAFFIC: 'true'
  #   ports:
  #   # Expose the WebSocket proxy port to the host machine,
  #   # this is where @vercel/postgres will connect
  #     - '54330:80'
  #   depends_on:
  #     - postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080