name: seed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: production
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}

jobs:
  migrate-seed: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'pnpm'
      - name: Migrate database
        run: |
          echo "Migrating database..."
          pnpm install
          pnpm db:generate
          pnpm db:seed:deck